KarateTournamentSoftware/Areas/Identity/Pages/Account/Login.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace KarateTournamentSoftware.Areas.Identity.Pages.Account {
    public class LoginModel : PageModel {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger) {
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel? Input { get; set; }

        public static bool ShowExternalLogins = false;
        public IList<AuthenticationScheme>? ExternalLogins { get; set; }

        public string? ReturnUrl { get; set; }

        [TempData]
        public string? ErrorMessage { get; set; }

        public class InputModel {
            [Required]
            [EmailAddress]
            public string? Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string? Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string? returnUrl = null) {
            if (!string.IsNullOrEmpty(ErrorMessage)) {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            if (ShowExternalLogins)
                ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string? returnUrl = null) {
            returnUrl ??= Url.Content("~/");

            if (ShowExternalLogins)
                ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            if (ModelState.IsValid) {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input?.Email!, Input?.Password!, Input!.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded) {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor) {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input?.RememberMe });
                }
                if (result.IsLockedOut) {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                } else {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

KarateTournamentSoftware/Controllers/EnrollmentController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KarateTournamentSoftware.Controllers {
    [Authorize(Roles = Other.Constants.RoleNameRoleAdmin)]
    public class EnrollmentController : Controller {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;
        public EnrollmentController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager) {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        // GET: EnrollmentController
        public async Task<IActionResult> Index() {
            var usersInRoles = new Dictionary<string, IList<IdentityUser>>();
            foreach (var role in roleManager.Roles.ToList()) { // .ToList() otherwise we get `There is already an open DataReader associated with this Connection which must be closed first.`
                usersInRoles.Add(role.Name!, await userManager.GetUsersInRoleAsync(role.Name!));
            }
            return View(usersInRoles);
        }

        // GET: EnrollmentController/Create
        public IActionResult Create() {
            var roles = roleManager.Roles.Select(r => r.Name).ToList();
            var users = userManager.Users.ToList();
            return View((Roles: roles, Users: users));
        }
        // POST: EnrollmentController/Create {role="roleName", user="userID"}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection collection) {
            try {
                var roleName = collection["role"];
                var userID = collection["user"];
                var user = await userManager.FindByIdAsync(userID!);

                await userManager.AddToRoleAsync(user!, roleName!);
                return RedirectToAction(nameof(Index));
            } catch (System.Exception ex) {
                return BadRequest($"{ex.GetType().FullName}: {ex.Message}");
            }
        }

        // POST: EnrollmentController/Delete/5 {user="userID"}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string roleName, IFormCollection collection) {
            try {
                var userID = collection["user"];
                var user = await userManager.FindByIdAsync(userID!);

                await userManager.RemoveFromRoleAsync(user!, roleName);
                return RedirectToAction(nameof(Index));
            } catch (System.Exception ex) {
                return BadRequest($"{ex.GetType().FullName}: {ex.Message}");
            }
        }

        // GET: EnrollmentController/Users
        public async Task<IActionResult> Users() {
            var users = await userManager.Users.ToListAsync();
            return View(users);
        }

        // POST: EnrollmentController/DeleteUser/{userID}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(string userID) {
            try {
                var user = await userManager.FindByIdAsync(userID);

                await userManager.DeleteAsync(user!);
                return RedirectToAction(nameof(Users));
            } catch (System.Exception ex) {
                return BadRequest($"{ex.GetType().FullName}: {ex.Message}");
            }
        }
    }
}

KarateTournamentSoftware/Views/Shared/Partials/_Login.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>
    </li>
    <li class="nav-item">
        <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <button id="logout" type="submit" class="nav-link btn btn-link text-dark border-0">Logout</button>
        </form>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Login</a>
    </li>
}
</ul>

KarateTournamentSoftware/Views/Shared/Partials/_Navbar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@KarateTournamentSoftware.Other.Constants.AppName</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (User.IsInRole(KarateTournamentSoftware.Other.Constants.RoleNameRoleAdmin)) {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrollment" asp-action="Index">Enrollments</a>
                        </li>
                    }
                </ul>
                <partial name="Partials/_Login" />
            </div>
        </div>
    </nav>
</header>

KarateTournamentSoftware/Views/Shared/Partials/_ValidationScripts.cshtml
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>